// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    entity_type, entity_id, action, performed_by, old_data, new_data
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, entity_type, entity_id, action, performed_by, old_data, new_data, created_at
`

type CreateAuditLogParams struct {
	EntityType  string                `json:"entity_type"`
	EntityID    uuid.UUID             `json:"entity_id"`
	Action      string                `json:"action"`
	PerformedBy uuid.NullUUID         `json:"performed_by"`
	OldData     pqtype.NullRawMessage `json:"old_data"`
	NewData     pqtype.NullRawMessage `json:"new_data"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.PerformedBy,
		arg.OldData,
		arg.NewData,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.PerformedBy,
		&i.OldData,
		&i.NewData,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByAction = `-- name: ListAuditLogsByAction :many
SELECT id, entity_type, entity_id, action, performed_by, old_data, new_data, created_at FROM audit_logs
WHERE action = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAuditLogsByAction(ctx context.Context, action string) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByAction, action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.PerformedBy,
			&i.OldData,
			&i.NewData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT id, entity_type, entity_id, action, performed_by, old_data, new_data, created_at FROM audit_logs
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
`

type ListAuditLogsByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.PerformedBy,
			&i.OldData,
			&i.NewData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, entity_type, entity_id, action, performed_by, old_data, new_data, created_at FROM audit_logs
WHERE performed_by = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAuditLogsByUser(ctx context.Context, performedBy uuid.NullUUID) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByUser, performedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.PerformedBy,
			&i.OldData,
			&i.NewData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
