// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contracts.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createContractDefinition = `-- name: CreateContractDefinition :one
INSERT INTO contract_definitions (
  roadmap_item_id, contract_type, version, input_schema, output_schema, error_schema, backward_compatible, deprecated_fields
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, roadmap_item_id, contract_type, version, input_schema, output_schema, error_schema, backward_compatible, deprecated_fields, created_at
`

type CreateContractDefinitionParams struct {
	RoadmapItemID      uuid.UUID             `json:"roadmap_item_id"`
	ContractType       ContractType          `json:"contract_type"`
	Version            string                `json:"version"`
	InputSchema        pqtype.NullRawMessage `json:"input_schema"`
	OutputSchema       pqtype.NullRawMessage `json:"output_schema"`
	ErrorSchema        pqtype.NullRawMessage `json:"error_schema"`
	BackwardCompatible sql.NullBool          `json:"backward_compatible"`
	DeprecatedFields   pqtype.NullRawMessage `json:"deprecated_fields"`
}

func (q *Queries) CreateContractDefinition(ctx context.Context, arg CreateContractDefinitionParams) (ContractDefinition, error) {
	row := q.db.QueryRowContext(ctx, createContractDefinition,
		arg.RoadmapItemID,
		arg.ContractType,
		arg.Version,
		arg.InputSchema,
		arg.OutputSchema,
		arg.ErrorSchema,
		arg.BackwardCompatible,
		arg.DeprecatedFields,
	)
	var i ContractDefinition
	err := row.Scan(
		&i.ID,
		&i.RoadmapItemID,
		&i.ContractType,
		&i.Version,
		&i.InputSchema,
		&i.OutputSchema,
		&i.ErrorSchema,
		&i.BackwardCompatible,
		&i.DeprecatedFields,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContractDefinition = `-- name: DeleteContractDefinition :exec
DELETE FROM contract_definitions
WHERE id = $1
`

func (q *Queries) DeleteContractDefinition(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteContractDefinition, id)
	return err
}

const getContractDefinition = `-- name: GetContractDefinition :one
SELECT id, roadmap_item_id, contract_type, version, input_schema, output_schema, error_schema, backward_compatible, deprecated_fields, created_at FROM contract_definitions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetContractDefinition(ctx context.Context, id uuid.UUID) (ContractDefinition, error) {
	row := q.db.QueryRowContext(ctx, getContractDefinition, id)
	var i ContractDefinition
	err := row.Scan(
		&i.ID,
		&i.RoadmapItemID,
		&i.ContractType,
		&i.Version,
		&i.InputSchema,
		&i.OutputSchema,
		&i.ErrorSchema,
		&i.BackwardCompatible,
		&i.DeprecatedFields,
		&i.CreatedAt,
	)
	return i, err
}

const listContractDefinitions = `-- name: ListContractDefinitions :many
SELECT id, roadmap_item_id, contract_type, version, input_schema, output_schema, error_schema, backward_compatible, deprecated_fields, created_at FROM contract_definitions
WHERE roadmap_item_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListContractDefinitions(ctx context.Context, roadmapItemID uuid.UUID) ([]ContractDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listContractDefinitions, roadmapItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContractDefinition
	for rows.Next() {
		var i ContractDefinition
		if err := rows.Scan(
			&i.ID,
			&i.RoadmapItemID,
			&i.ContractType,
			&i.Version,
			&i.InputSchema,
			&i.OutputSchema,
			&i.ErrorSchema,
			&i.BackwardCompatible,
			&i.DeprecatedFields,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractDefinitionsByProject = `-- name: ListContractDefinitionsByProject :many
SELECT cd.id, cd.roadmap_item_id, cd.contract_type, cd.version, cd.input_schema, cd.output_schema, cd.error_schema, cd.backward_compatible, cd.deprecated_fields, cd.created_at FROM contract_definitions cd
JOIN roadmap_items ri ON cd.roadmap_item_id = ri.id
WHERE ri.project_id = $1
ORDER BY cd.created_at DESC
`

func (q *Queries) ListContractDefinitionsByProject(ctx context.Context, projectID uuid.UUID) ([]ContractDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listContractDefinitionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContractDefinition
	for rows.Next() {
		var i ContractDefinition
		if err := rows.Scan(
			&i.ID,
			&i.RoadmapItemID,
			&i.ContractType,
			&i.Version,
			&i.InputSchema,
			&i.OutputSchema,
			&i.ErrorSchema,
			&i.BackwardCompatible,
			&i.DeprecatedFields,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContractDefinition = `-- name: UpdateContractDefinition :one
UPDATE contract_definitions SET
  contract_type = $2,
  version = $3,
  input_schema = $4,
  output_schema = $5,
  error_schema = $6,
  backward_compatible = $7,
  deprecated_fields = $8
WHERE id = $1
RETURNING id, roadmap_item_id, contract_type, version, input_schema, output_schema, error_schema, backward_compatible, deprecated_fields, created_at
`

type UpdateContractDefinitionParams struct {
	ID                 uuid.UUID             `json:"id"`
	ContractType       ContractType          `json:"contract_type"`
	Version            string                `json:"version"`
	InputSchema        pqtype.NullRawMessage `json:"input_schema"`
	OutputSchema       pqtype.NullRawMessage `json:"output_schema"`
	ErrorSchema        pqtype.NullRawMessage `json:"error_schema"`
	BackwardCompatible sql.NullBool          `json:"backward_compatible"`
	DeprecatedFields   pqtype.NullRawMessage `json:"deprecated_fields"`
}

func (q *Queries) UpdateContractDefinition(ctx context.Context, arg UpdateContractDefinitionParams) (ContractDefinition, error) {
	row := q.db.QueryRowContext(ctx, updateContractDefinition,
		arg.ID,
		arg.ContractType,
		arg.Version,
		arg.InputSchema,
		arg.OutputSchema,
		arg.ErrorSchema,
		arg.BackwardCompatible,
		arg.DeprecatedFields,
	)
	var i ContractDefinition
	err := row.Scan(
		&i.ID,
		&i.RoadmapItemID,
		&i.ContractType,
		&i.Version,
		&i.InputSchema,
		&i.OutputSchema,
		&i.ErrorSchema,
		&i.BackwardCompatible,
		&i.DeprecatedFields,
		&i.CreatedAt,
	)
	return i, err
}
