// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import_sessions.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createImportArtifact = `-- name: CreateImportArtifact :one
INSERT INTO project_import_artifacts (
    session_id,
    payload
) VALUES (
    $1, $2
) RETURNING id, session_id, payload, created_at
`

type CreateImportArtifactParams struct {
	SessionID uuid.UUID       `json:"session_id"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) CreateImportArtifact(ctx context.Context, arg CreateImportArtifactParams) (ProjectImportArtifact, error) {
	row := q.db.QueryRowContext(ctx, createImportArtifact, arg.SessionID, arg.Payload)
	var i ProjectImportArtifact
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createImportSession = `-- name: CreateImportSession :one
INSERT INTO project_import_sessions (
    project_id,
    completeness_score,
    status,
    iteration_count,
    locked
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, project_id, completeness_score, status, iteration_count, locked, created_at, updated_at
`

type CreateImportSessionParams struct {
	ProjectID         uuid.UUID    `json:"project_id"`
	CompletenessScore int32        `json:"completeness_score"`
	Status            ImportStatus `json:"status"`
	IterationCount    int32        `json:"iteration_count"`
	Locked            bool         `json:"locked"`
}

func (q *Queries) CreateImportSession(ctx context.Context, arg CreateImportSessionParams) (ProjectImportSession, error) {
	row := q.db.QueryRowContext(ctx, createImportSession,
		arg.ProjectID,
		arg.CompletenessScore,
		arg.Status,
		arg.IterationCount,
		arg.Locked,
	)
	var i ProjectImportSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CompletenessScore,
		&i.Status,
		&i.IterationCount,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportSession = `-- name: GetImportSession :one
SELECT id, project_id, completeness_score, status, iteration_count, locked, created_at, updated_at FROM project_import_sessions
WHERE id = $1
`

func (q *Queries) GetImportSession(ctx context.Context, id uuid.UUID) (ProjectImportSession, error) {
	row := q.db.QueryRowContext(ctx, getImportSession, id)
	var i ProjectImportSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CompletenessScore,
		&i.Status,
		&i.IterationCount,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestImportSessionByProject = `-- name: GetLatestImportSessionByProject :one
SELECT id, project_id, completeness_score, status, iteration_count, locked, created_at, updated_at FROM project_import_sessions
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestImportSessionByProject(ctx context.Context, projectID uuid.UUID) (ProjectImportSession, error) {
	row := q.db.QueryRowContext(ctx, getLatestImportSessionByProject, projectID)
	var i ProjectImportSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CompletenessScore,
		&i.Status,
		&i.IterationCount,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listImportArtifactsBySession = `-- name: ListImportArtifactsBySession :many
SELECT id, session_id, payload, created_at FROM project_import_artifacts
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListImportArtifactsBySession(ctx context.Context, sessionID uuid.UUID) ([]ProjectImportArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listImportArtifactsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectImportArtifact
	for rows.Next() {
		var i ProjectImportArtifact
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportSession = `-- name: UpdateImportSession :one
UPDATE project_import_sessions
SET 
    completeness_score = $2,
    status = $3,
    iteration_count = $4,
    locked = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, project_id, completeness_score, status, iteration_count, locked, created_at, updated_at
`

type UpdateImportSessionParams struct {
	ID                uuid.UUID    `json:"id"`
	CompletenessScore int32        `json:"completeness_score"`
	Status            ImportStatus `json:"status"`
	IterationCount    int32        `json:"iteration_count"`
	Locked            bool         `json:"locked"`
}

func (q *Queries) UpdateImportSession(ctx context.Context, arg UpdateImportSessionParams) (ProjectImportSession, error) {
	row := q.db.QueryRowContext(ctx, updateImportSession,
		arg.ID,
		arg.CompletenessScore,
		arg.Status,
		arg.IterationCount,
		arg.Locked,
	)
	var i ProjectImportSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CompletenessScore,
		&i.Status,
		&i.IterationCount,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
