// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ContractType string

const (
	ContractTypeREST             ContractType = "REST"
	ContractTypeGRAPHQL          ContractType = "GRAPHQL"
	ContractTypeCLI              ContractType = "CLI"
	ContractTypeINTERNALFUNCTION ContractType = "INTERNAL_FUNCTION"
	ContractTypeEVENT            ContractType = "EVENT"
)

func (e *ContractType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContractType(s)
	case string:
		*e = ContractType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContractType: %T", src)
	}
	return nil
}

type NullContractType struct {
	ContractType ContractType `json:"contract_type"`
	Valid        bool         `json:"valid"` // Valid is true if ContractType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContractType) Scan(value interface{}) error {
	if value == nil {
		ns.ContractType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContractType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContractType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContractType), nil
}

type ImportStatus string

const (
	ImportStatusPartial  ImportStatus = "partial"
	ImportStatusComplete ImportStatus = "complete"
)

func (e *ImportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportStatus(s)
	case string:
		*e = ImportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportStatus: %T", src)
	}
	return nil
}

type NullImportStatus struct {
	ImportStatus ImportStatus `json:"import_status"`
	Valid        bool         `json:"valid"` // Valid is true if ImportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportStatus), nil
}

type ProposalStatus string

const (
	ProposalStatusPENDING  ProposalStatus = "PENDING"
	ProposalStatusAPPROVED ProposalStatus = "APPROVED"
	ProposalStatusREJECTED ProposalStatus = "REJECTED"
)

func (e *ProposalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProposalStatus(s)
	case string:
		*e = ProposalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProposalStatus: %T", src)
	}
	return nil
}

type NullProposalStatus struct {
	ProposalStatus ProposalStatus `json:"proposal_status"`
	Valid          bool           `json:"valid"` // Valid is true if ProposalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProposalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProposalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProposalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProposalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProposalStatus), nil
}

type ProposalType string

const (
	ProposalTypeEDITDESCRIPTION ProposalType = "EDIT_DESCRIPTION"
	ProposalTypeMODIFYSCHEMA    ProposalType = "MODIFY_SCHEMA"
	ProposalTypeADDVARIABLE     ProposalType = "ADD_VARIABLE"
	ProposalTypeREMOVEFIELD     ProposalType = "REMOVE_FIELD"
)

func (e *ProposalType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProposalType(s)
	case string:
		*e = ProposalType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProposalType: %T", src)
	}
	return nil
}

type NullProposalType struct {
	ProposalType ProposalType `json:"proposal_type"`
	Valid        bool         `json:"valid"` // Valid is true if ProposalType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProposalType) Scan(value interface{}) error {
	if value == nil {
		ns.ProposalType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProposalType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProposalType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProposalType), nil
}

type RiskLevel string

const (
	RiskLevelLOW    RiskLevel = "LOW"
	RiskLevelMEDIUM RiskLevel = "MEDIUM"
	RiskLevelHIGH   RiskLevel = "HIGH"
)

func (e *RiskLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiskLevel(s)
	case string:
		*e = RiskLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for RiskLevel: %T", src)
	}
	return nil
}

type NullRiskLevel struct {
	RiskLevel RiskLevel `json:"risk_level"`
	Valid     bool      `json:"valid"` // Valid is true if RiskLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiskLevel) Scan(value interface{}) error {
	if value == nil {
		ns.RiskLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiskLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiskLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiskLevel), nil
}

type RoadmapItemPriority string

const (
	RoadmapItemPriorityLOW      RoadmapItemPriority = "LOW"
	RoadmapItemPriorityMEDIUM   RoadmapItemPriority = "MEDIUM"
	RoadmapItemPriorityHIGH     RoadmapItemPriority = "HIGH"
	RoadmapItemPriorityCRITICAL RoadmapItemPriority = "CRITICAL"
)

func (e *RoadmapItemPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoadmapItemPriority(s)
	case string:
		*e = RoadmapItemPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for RoadmapItemPriority: %T", src)
	}
	return nil
}

type NullRoadmapItemPriority struct {
	RoadmapItemPriority RoadmapItemPriority `json:"roadmap_item_priority"`
	Valid               bool                `json:"valid"` // Valid is true if RoadmapItemPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoadmapItemPriority) Scan(value interface{}) error {
	if value == nil {
		ns.RoadmapItemPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoadmapItemPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoadmapItemPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoadmapItemPriority), nil
}

type RoadmapItemStatus string

const (
	RoadmapItemStatusDRAFT      RoadmapItemStatus = "DRAFT"
	RoadmapItemStatusINREVIEW   RoadmapItemStatus = "IN_REVIEW"
	RoadmapItemStatusAPPROVED   RoadmapItemStatus = "APPROVED"
	RoadmapItemStatusINPROGRESS RoadmapItemStatus = "IN_PROGRESS"
	RoadmapItemStatusCOMPLETE   RoadmapItemStatus = "COMPLETE"
)

func (e *RoadmapItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoadmapItemStatus(s)
	case string:
		*e = RoadmapItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RoadmapItemStatus: %T", src)
	}
	return nil
}

type NullRoadmapItemStatus struct {
	RoadmapItemStatus RoadmapItemStatus `json:"roadmap_item_status"`
	Valid             bool              `json:"valid"` // Valid is true if RoadmapItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoadmapItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RoadmapItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoadmapItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoadmapItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoadmapItemStatus), nil
}

type RoadmapItemType string

const (
	RoadmapItemTypeEPIC     RoadmapItemType = "EPIC"
	RoadmapItemTypeFEATURE  RoadmapItemType = "FEATURE"
	RoadmapItemTypeTASK     RoadmapItemType = "TASK"
	RoadmapItemTypeBUGFIX   RoadmapItemType = "BUGFIX"
	RoadmapItemTypeREFACTOR RoadmapItemType = "REFACTOR"
)

func (e *RoadmapItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoadmapItemType(s)
	case string:
		*e = RoadmapItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoadmapItemType: %T", src)
	}
	return nil
}

type NullRoadmapItemType struct {
	RoadmapItemType RoadmapItemType `json:"roadmap_item_type"`
	Valid           bool            `json:"valid"` // Valid is true if RoadmapItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoadmapItemType) Scan(value interface{}) error {
	if value == nil {
		ns.RoadmapItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoadmapItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoadmapItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoadmapItemType), nil
}

type AiProposal struct {
	ID              uuid.UUID          `json:"id"`
	RoadmapItemID   uuid.UUID          `json:"roadmap_item_id"`
	ProposalType    ProposalType       `json:"proposal_type"`
	Diff            json.RawMessage    `json:"diff"`
	Reasoning       sql.NullString     `json:"reasoning"`
	ConfidenceScore sql.NullFloat64    `json:"confidence_score"`
	Status          NullProposalStatus `json:"status"`
	ReviewedBy      uuid.NullUUID      `json:"reviewed_by"`
	CreatedAt       sql.NullTime       `json:"created_at"`
}

type AlignmentReport struct {
	ID                     uuid.UUID             `json:"id"`
	ProjectID              uuid.UUID             `json:"project_id"`
	Conflicts              pqtype.NullRawMessage `json:"conflicts"`
	Overlaps               pqtype.NullRawMessage `json:"overlaps"`
	MissingDependencies    pqtype.NullRawMessage `json:"missing_dependencies"`
	CircularDependencies   pqtype.NullRawMessage `json:"circular_dependencies"`
	RecommendedResolutions pqtype.NullRawMessage `json:"recommended_resolutions"`
	AlignmentScore         int32                 `json:"alignment_score"`
	CreatedAt              sql.NullTime          `json:"created_at"`
}

type AuditLog struct {
	ID          uuid.UUID             `json:"id"`
	EntityType  string                `json:"entity_type"`
	EntityID    uuid.UUID             `json:"entity_id"`
	Action      string                `json:"action"`
	PerformedBy uuid.NullUUID         `json:"performed_by"`
	OldData     pqtype.NullRawMessage `json:"old_data"`
	NewData     pqtype.NullRawMessage `json:"new_data"`
	CreatedAt   sql.NullTime          `json:"created_at"`
}

type ContractDefinition struct {
	ID                 uuid.UUID             `json:"id"`
	RoadmapItemID      uuid.UUID             `json:"roadmap_item_id"`
	ContractType       ContractType          `json:"contract_type"`
	Version            string                `json:"version"`
	InputSchema        pqtype.NullRawMessage `json:"input_schema"`
	OutputSchema       pqtype.NullRawMessage `json:"output_schema"`
	ErrorSchema        pqtype.NullRawMessage `json:"error_schema"`
	BackwardCompatible sql.NullBool          `json:"backward_compatible"`
	DeprecatedFields   pqtype.NullRawMessage `json:"deprecated_fields"`
	CreatedAt          sql.NullTime          `json:"created_at"`
}

type FeatureIntelligence struct {
	ID                       uuid.UUID    `json:"id"`
	FeatureID                uuid.UUID    `json:"feature_id"`
	CompletenessScore        int32        `json:"completeness_score"`
	ContractIntegrityScore   int32        `json:"contract_integrity_score"`
	VariableCoverageScore    int32        `json:"variable_coverage_score"`
	DependencyStabilityScore int32        `json:"dependency_stability_score"`
	DriftRiskScore           int32        `json:"drift_risk_score"`
	TestCoverageScore        int32        `json:"test_coverage_score"`
	LlmConfidenceScore       int32        `json:"llm_confidence_score"`
	OverallScore             int32        `json:"overall_score"`
	LastCalculatedAt         sql.NullTime `json:"last_calculated_at"`
}

type LlmConfiguration struct {
	ID        uuid.UUID      `json:"id"`
	Provider  interface{}    `json:"provider"`
	ApiKey    string         `json:"api_key"`
	BaseUrl   sql.NullString `json:"base_url"`
	Model     string         `json:"model"`
	IsActive  bool           `json:"is_active"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type McpApiToken struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	ProjectID   uuid.UUID    `json:"project_id"`
	TokenHash   string       `json:"token_hash"`
	TokenPrefix string       `json:"token_prefix"`
	Revoked     bool         `json:"revoked"`
	LastUsedAt  sql.NullTime `json:"last_used_at"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Project struct {
	ID               uuid.UUID             `json:"id"`
	WorkspaceID      uuid.UUID             `json:"workspace_id"`
	Name             string                `json:"name"`
	Description      sql.NullString        `json:"description"`
	TechStack        pqtype.NullRawMessage `json:"tech_stack"`
	RepositoryUrl    sql.NullString        `json:"repository_url"`
	CreatedAt        sql.NullTime          `json:"created_at"`
	UpdatedAt        sql.NullTime          `json:"updated_at"`
	Settings         pqtype.NullRawMessage `json:"settings"`
	AlignmentScore   sql.NullInt32         `json:"alignment_score"`
	McpEnabled       sql.NullBool          `json:"mcp_enabled"`
	McpPort          sql.NullInt32         `json:"mcp_port"`
	McpBindAddress   sql.NullString        `json:"mcp_bind_address"`
	McpTokenRequired sql.NullBool          `json:"mcp_token_required"`
	McpToken         sql.NullString        `json:"mcp_token"`
}

type ProjectApiIndex struct {
	ID             uuid.UUID             `json:"id"`
	ProjectID      uuid.UUID             `json:"project_id"`
	SnapshotID     uuid.UUID             `json:"snapshot_id"`
	Endpoint       string                `json:"endpoint"`
	Method         string                `json:"method"`
	AuthType       sql.NullString        `json:"auth_type"`
	RequestSchema  pqtype.NullRawMessage `json:"request_schema"`
	ResponseSchema pqtype.NullRawMessage `json:"response_schema"`
}

type ProjectContractRegistry struct {
	ID             uuid.UUID             `json:"id"`
	ProjectID      uuid.UUID             `json:"project_id"`
	SnapshotID     uuid.UUID             `json:"snapshot_id"`
	Name           string                `json:"name"`
	ContractType   sql.NullString        `json:"contract_type"`
	SchemaJson     pqtype.NullRawMessage `json:"schema_json"`
	SourceModule   sql.NullString        `json:"source_module"`
	StabilityScore sql.NullString        `json:"stability_score"`
}

type ProjectEntity struct {
	ID                uuid.UUID             `json:"id"`
	ProjectID         uuid.UUID             `json:"project_id"`
	SnapshotID        uuid.UUID             `json:"snapshot_id"`
	Name              string                `json:"name"`
	RelationshipsJson pqtype.NullRawMessage `json:"relationships_json"`
	ConstraintsJson   pqtype.NullRawMessage `json:"constraints_json"`
}

type ProjectImportArtifact struct {
	ID        uuid.UUID       `json:"id"`
	SessionID uuid.UUID       `json:"session_id"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type ProjectImportSession struct {
	ID                uuid.UUID    `json:"id"`
	ProjectID         uuid.UUID    `json:"project_id"`
	CompletenessScore int32        `json:"completeness_score"`
	Status            ImportStatus `json:"status"`
	IterationCount    int32        `json:"iteration_count"`
	Locked            bool         `json:"locked"`
	CreatedAt         sql.NullTime `json:"created_at"`
	UpdatedAt         sql.NullTime `json:"updated_at"`
}

type ProjectIntelligenceSnapshot struct {
	ID                uuid.UUID             `json:"id"`
	ProjectID         uuid.UUID             `json:"project_id"`
	Version           int32                 `json:"version"`
	SnapshotJson      json.RawMessage       `json:"snapshot_json"`
	ArchitectureScore sql.NullString        `json:"architecture_score"`
	ContractDensity   sql.NullString        `json:"contract_density"`
	RiskScore         sql.NullString        `json:"risk_score"`
	AlignmentScore    sql.NullString        `json:"alignment_score"`
	ConfidenceJson    pqtype.NullRawMessage `json:"confidence_json"`
	CreatedAt         time.Time             `json:"created_at"`
}

type ProjectModule struct {
	ID                uuid.UUID      `json:"id"`
	ProjectID         uuid.UUID      `json:"project_id"`
	SnapshotID        uuid.UUID      `json:"snapshot_id"`
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	RiskLevel         sql.NullString `json:"risk_level"`
	ChangeSensitivity sql.NullString `json:"change_sensitivity"`
}

type RealitySnapshot struct {
	ID            uuid.UUID             `json:"id"`
	ProjectID     uuid.UUID             `json:"project_id"`
	RoadmapItemID uuid.UUID             `json:"roadmap_item_id"`
	State         interface{}           `json:"state"`
	SnapshotJson  pqtype.NullRawMessage `json:"snapshot_json"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	UpdatedAt     sql.NullTime          `json:"updated_at"`
}

type RefinementIteration struct {
	ID               uuid.UUID             `json:"id"`
	SessionID        uuid.UUID             `json:"session_id"`
	Iteration        int32                 `json:"iteration"`
	Prompt           string                `json:"prompt"`
	Response         string                `json:"response"`
	Artifact         pqtype.NullRawMessage `json:"artifact"`
	ValidationResult pqtype.NullRawMessage `json:"validation_result"`
	CreatedAt        sql.NullTime          `json:"created_at"`
}

type RefinementSession struct {
	ID               uuid.UUID             `json:"id"`
	ArtifactType     string                `json:"artifact_type"`
	InitialPrompt    string                `json:"initial_prompt"`
	ContextData      pqtype.NullRawMessage `json:"context_data"`
	MaxIterations    int32                 `json:"max_iterations"`
	CurrentIteration int32                 `json:"current_iteration"`
	Status           interface{}           `json:"status"`
	ConfidenceScore  sql.NullFloat64       `json:"confidence_score"`
	ValidationErrors []string              `json:"validation_errors"`
	Result           pqtype.NullRawMessage `json:"result"`
	CreatedAt        sql.NullTime          `json:"created_at"`
	UpdatedAt        sql.NullTime          `json:"updated_at"`
}

type Requirement struct {
	ID                 uuid.UUID      `json:"id"`
	RoadmapItemID      uuid.UUID      `json:"roadmap_item_id"`
	Title              string         `json:"title"`
	Description        sql.NullString `json:"description"`
	Testable           sql.NullBool   `json:"testable"`
	AcceptanceCriteria sql.NullString `json:"acceptance_criteria"`
	OrderIndex         sql.NullInt32  `json:"order_index"`
}

type RoadmapDependency struct {
	ID             uuid.UUID    `json:"id"`
	SourceID       uuid.UUID    `json:"source_id"`
	TargetID       uuid.UUID    `json:"target_id"`
	DependencyType string       `json:"dependency_type"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type RoadmapItem struct {
	ID                  uuid.UUID               `json:"id"`
	ProjectID           uuid.UUID               `json:"project_id"`
	Type                RoadmapItemType         `json:"type"`
	Title               string                  `json:"title"`
	Description         sql.NullString          `json:"description"`
	BusinessContext     sql.NullString          `json:"business_context"`
	TechnicalContext    sql.NullString          `json:"technical_context"`
	Priority            NullRoadmapItemPriority `json:"priority"`
	Status              NullRoadmapItemStatus   `json:"status"`
	RiskLevel           NullRiskLevel           `json:"risk_level"`
	BreakingChange      sql.NullBool            `json:"breaking_change"`
	RegressionSensitive sql.NullBool            `json:"regression_sensitive"`
	CreatedAt           sql.NullTime            `json:"created_at"`
	UpdatedAt           sql.NullTime            `json:"updated_at"`
	ReadinessLevel      sql.NullString          `json:"readiness_level"`
}

type SnapshotAnalysis struct {
	ID                 uuid.UUID             `json:"id"`
	SnapshotID         uuid.UUID             `json:"snapshot_id"`
	ScoresJson         json.RawMessage       `json:"scores_json"`
	Verdict            string                `json:"verdict"`
	DriftDetected      sql.NullBool          `json:"drift_detected"`
	AlignmentConflicts pqtype.NullRawMessage `json:"alignment_conflicts"`
	CreatedAt          sql.NullTime          `json:"created_at"`
}

type UiRoadmapItem struct {
	ID                uuid.UUID             `json:"id"`
	ProjectID         uuid.UUID             `json:"project_id"`
	LinkedFeatureID   uuid.NullUUID         `json:"linked_feature_id"`
	Name              string                `json:"name"`
	Description       sql.NullString        `json:"description"`
	UserPersona       sql.NullString        `json:"user_persona"`
	UseCase           sql.NullString        `json:"use_case"`
	ScreenType        sql.NullString        `json:"screen_type"`
	LayoutDefinition  pqtype.NullRawMessage `json:"layout_definition"`
	ComponentTree     pqtype.NullRawMessage `json:"component_tree"`
	StateMachine      pqtype.NullRawMessage `json:"state_machine"`
	BackendBindings   pqtype.NullRawMessage `json:"backend_bindings"`
	AccessibilitySpec pqtype.NullRawMessage `json:"accessibility_spec"`
	ResponsiveSpec    pqtype.NullRawMessage `json:"responsive_spec"`
	ValidationRules   pqtype.NullRawMessage `json:"validation_rules"`
	AnimationRules    pqtype.NullRawMessage `json:"animation_rules"`
	DesignTokensUsed  []string              `json:"design_tokens_used"`
	EdgeCases         pqtype.NullRawMessage `json:"edge_cases"`
	TestScenarios     pqtype.NullRawMessage `json:"test_scenarios"`
	IntelligenceScore sql.NullFloat64       `json:"intelligence_score"`
	Version           sql.NullInt32         `json:"version"`
	CreatedAt         sql.NullTime          `json:"created_at"`
	UpdatedAt         sql.NullTime          `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	FullName     sql.NullString `json:"full_name"`
	Role         string         `json:"role"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	PasswordHash sql.NullString `json:"password_hash"`
}

type ValidationRule struct {
	ID          uuid.UUID             `json:"id"`
	ProjectID   uuid.UUID             `json:"project_id"`
	Name        string                `json:"name"`
	RuleType    string                `json:"rule_type"`
	RuleConfig  pqtype.NullRawMessage `json:"rule_config"`
	Description sql.NullString        `json:"description"`
	CreatedAt   sql.NullTime          `json:"created_at"`
}

type VariableDefinition struct {
	ID              uuid.UUID             `json:"id"`
	ContractID      uuid.UUID             `json:"contract_id"`
	Name            string                `json:"name"`
	Type            string                `json:"type"`
	Required        sql.NullBool          `json:"required"`
	DefaultValue    sql.NullString        `json:"default_value"`
	Description     sql.NullString        `json:"description"`
	ValidationRules pqtype.NullRawMessage `json:"validation_rules"`
}

type VariableDependency struct {
	ID               uuid.UUID    `json:"id"`
	SourceVariableID uuid.UUID    `json:"source_variable_id"`
	TargetVariableID uuid.UUID    `json:"target_variable_id"`
	DependencyType   interface{}  `json:"dependency_type"`
	CreatedAt        sql.NullTime `json:"created_at"`
}

type VariableLineageEvent struct {
	ID              uuid.UUID             `json:"id"`
	VariableID      uuid.UUID             `json:"variable_id"`
	EventType       interface{}           `json:"event_type"`
	SourceComponent string                `json:"source_component"`
	Description     string                `json:"description"`
	PerformedBy     uuid.NullUUID         `json:"performed_by"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
}

type VersionSnapshot struct {
	ID            uuid.UUID       `json:"id"`
	RoadmapItemID uuid.UUID       `json:"roadmap_item_id"`
	SnapshotData  json.RawMessage `json:"snapshot_data"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	CreatedBy     uuid.NullUUID   `json:"created_by"`
}

type Webhook struct {
	ID        uuid.UUID    `json:"id"`
	ProjectID uuid.UUID    `json:"project_id"`
	Url       string       `json:"url"`
	Events    []string     `json:"events"`
	Secret    string       `json:"secret"`
	Active    sql.NullBool `json:"active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Workspace struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
