// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
  workspace_id, name, description, tech_stack, settings, repository_url,
  mcp_enabled, mcp_port, mcp_bind_address, mcp_token_required, mcp_token
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, workspace_id, name, description, tech_stack, repository_url, created_at, updated_at, settings, alignment_score, mcp_enabled, mcp_port, mcp_bind_address, mcp_token_required, mcp_token
`

type CreateProjectParams struct {
	WorkspaceID      uuid.UUID             `json:"workspace_id"`
	Name             string                `json:"name"`
	Description      sql.NullString        `json:"description"`
	TechStack        pqtype.NullRawMessage `json:"tech_stack"`
	Settings         pqtype.NullRawMessage `json:"settings"`
	RepositoryUrl    sql.NullString        `json:"repository_url"`
	McpEnabled       sql.NullBool          `json:"mcp_enabled"`
	McpPort          sql.NullInt32         `json:"mcp_port"`
	McpBindAddress   sql.NullString        `json:"mcp_bind_address"`
	McpTokenRequired sql.NullBool          `json:"mcp_token_required"`
	McpToken         sql.NullString        `json:"mcp_token"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.TechStack,
		arg.Settings,
		arg.RepositoryUrl,
		arg.McpEnabled,
		arg.McpPort,
		arg.McpBindAddress,
		arg.McpTokenRequired,
		arg.McpToken,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.TechStack,
		&i.RepositoryUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.AlignmentScore,
		&i.McpEnabled,
		&i.McpPort,
		&i.McpBindAddress,
		&i.McpTokenRequired,
		&i.McpToken,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, workspace_id, name, description, tech_stack, repository_url, created_at, updated_at, settings, alignment_score, mcp_enabled, mcp_port, mcp_bind_address, mcp_token_required, mcp_token FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.TechStack,
		&i.RepositoryUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.AlignmentScore,
		&i.McpEnabled,
		&i.McpPort,
		&i.McpBindAddress,
		&i.McpTokenRequired,
		&i.McpToken,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, workspace_id, name, description, tech_stack, repository_url, created_at, updated_at, settings, alignment_score, mcp_enabled, mcp_port, mcp_bind_address, mcp_token_required, mcp_token FROM projects
WHERE workspace_id = $1
ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context, workspaceID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.TechStack,
			&i.RepositoryUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Settings,
			&i.AlignmentScore,
			&i.McpEnabled,
			&i.McpPort,
			&i.McpBindAddress,
			&i.McpTokenRequired,
			&i.McpToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
  set name = $2,
  description = $3,
  tech_stack = $4,
  settings = $5,
  repository_url = $6,
  mcp_enabled = $7,
  mcp_port = $8,
  mcp_bind_address = $9,
  mcp_token_required = $10,
  mcp_token = $11
WHERE id = $1
RETURNING id, workspace_id, name, description, tech_stack, repository_url, created_at, updated_at, settings, alignment_score, mcp_enabled, mcp_port, mcp_bind_address, mcp_token_required, mcp_token
`

type UpdateProjectParams struct {
	ID               uuid.UUID             `json:"id"`
	Name             string                `json:"name"`
	Description      sql.NullString        `json:"description"`
	TechStack        pqtype.NullRawMessage `json:"tech_stack"`
	Settings         pqtype.NullRawMessage `json:"settings"`
	RepositoryUrl    sql.NullString        `json:"repository_url"`
	McpEnabled       sql.NullBool          `json:"mcp_enabled"`
	McpPort          sql.NullInt32         `json:"mcp_port"`
	McpBindAddress   sql.NullString        `json:"mcp_bind_address"`
	McpTokenRequired sql.NullBool          `json:"mcp_token_required"`
	McpToken         sql.NullString        `json:"mcp_token"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TechStack,
		arg.Settings,
		arg.RepositoryUrl,
		arg.McpEnabled,
		arg.McpPort,
		arg.McpBindAddress,
		arg.McpTokenRequired,
		arg.McpToken,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.TechStack,
		&i.RepositoryUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.AlignmentScore,
		&i.McpEnabled,
		&i.McpPort,
		&i.McpBindAddress,
		&i.McpTokenRequired,
		&i.McpToken,
	)
	return i, err
}
