// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAiProposal(ctx context.Context, arg CreateAiProposalParams) (AiProposal, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateContractDefinition(ctx context.Context, arg CreateContractDefinitionParams) (ContractDefinition, error)
	CreateFeatureIntelligence(ctx context.Context, arg CreateFeatureIntelligenceParams) (FeatureIntelligence, error)
	CreateImportArtifact(ctx context.Context, arg CreateImportArtifactParams) (ProjectImportArtifact, error)
	CreateImportSession(ctx context.Context, arg CreateImportSessionParams) (ProjectImportSession, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRequirement(ctx context.Context, arg CreateRequirementParams) (Requirement, error)
	CreateRoadmapItem(ctx context.Context, arg CreateRoadmapItemParams) (RoadmapItem, error)
	CreateValidationRule(ctx context.Context, arg CreateValidationRuleParams) (ValidationRule, error)
	CreateVariable(ctx context.Context, arg CreateVariableParams) (VariableDefinition, error)
	CreateVariableDependency(ctx context.Context, arg CreateVariableDependencyParams) (VariableDependency, error)
	CreateVariableLineageEvent(ctx context.Context, arg CreateVariableLineageEventParams) (VariableLineageEvent, error)
	CreateVersionSnapshot(ctx context.Context, arg CreateVersionSnapshotParams) (VersionSnapshot, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteAiProposal(ctx context.Context, id uuid.UUID) error
	DeleteContractDefinition(ctx context.Context, id uuid.UUID) error
	DeleteFeatureIntelligence(ctx context.Context, featureID uuid.UUID) error
	DeleteProject(ctx context.Context, id uuid.UUID) error
	DeleteRequirement(ctx context.Context, id uuid.UUID) error
	DeleteRoadmapItem(ctx context.Context, id uuid.UUID) error
	DeleteValidationRule(ctx context.Context, id uuid.UUID) error
	DeleteVariable(ctx context.Context, id uuid.UUID) error
	DeleteVariableDependencies(ctx context.Context, sourceVariableID uuid.UUID) error
	DeleteVersionSnapshot(ctx context.Context, id uuid.UUID) error
	DeleteWebhook(ctx context.Context, id uuid.UUID) error
	DeleteWorkspace(ctx context.Context, id uuid.UUID) error
	GetAiProposal(ctx context.Context, id uuid.UUID) (AiProposal, error)
	GetContractDefinition(ctx context.Context, id uuid.UUID) (ContractDefinition, error)
	GetFeatureIntelligence(ctx context.Context, featureID uuid.UUID) (FeatureIntelligence, error)
	GetImportSession(ctx context.Context, id uuid.UUID) (ProjectImportSession, error)
	GetIntelligenceSnapshot(ctx context.Context, id uuid.UUID) (ProjectIntelligenceSnapshot, error)
	GetLatestImportSessionByProject(ctx context.Context, projectID uuid.UUID) (ProjectImportSession, error)
	GetLatestSnapshot(ctx context.Context, projectID uuid.UUID) (ProjectIntelligenceSnapshot, error)
	GetMaxSnapshotVersion(ctx context.Context, projectID uuid.UUID) (int32, error)
	GetProject(ctx context.Context, id uuid.UUID) (Project, error)
	GetRequirement(ctx context.Context, id uuid.UUID) (Requirement, error)
	GetRoadmapItem(ctx context.Context, id uuid.UUID) (RoadmapItem, error)
	GetValidationRule(ctx context.Context, id uuid.UUID) (ValidationRule, error)
	GetVariable(ctx context.Context, id uuid.UUID) (VariableDefinition, error)
	GetVariableDependencies(ctx context.Context, sourceVariableID uuid.UUID) ([]VariableDependency, error)
	GetVariableLineageEvents(ctx context.Context, variableID uuid.UUID) ([]VariableLineageEvent, error)
	GetVersionSnapshot(ctx context.Context, id uuid.UUID) (VersionSnapshot, error)
	GetWebhook(ctx context.Context, id uuid.UUID) (Webhook, error)
	GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	InsertIntelligenceSnapshot(ctx context.Context, arg InsertIntelligenceSnapshotParams) (ProjectIntelligenceSnapshot, error)
	InsertProjectApiEntry(ctx context.Context, arg InsertProjectApiEntryParams) (ProjectApiIndex, error)
	InsertProjectContractEntry(ctx context.Context, arg InsertProjectContractEntryParams) (ProjectContractRegistry, error)
	InsertProjectEntity(ctx context.Context, arg InsertProjectEntityParams) (ProjectEntity, error)
	InsertProjectModule(ctx context.Context, arg InsertProjectModuleParams) (ProjectModule, error)
	ListAiProposalsByProject(ctx context.Context, projectID uuid.UUID) ([]AiProposal, error)
	ListAiProposalsByRoadmapItem(ctx context.Context, roadmapItemID uuid.UUID) ([]AiProposal, error)
	ListApiEntriesBySnapshot(ctx context.Context, snapshotID uuid.UUID) ([]ProjectApiIndex, error)
	ListAuditLogsByAction(ctx context.Context, action string) ([]AuditLog, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, performedBy uuid.NullUUID) ([]AuditLog, error)
	ListContractDefinitions(ctx context.Context, roadmapItemID uuid.UUID) ([]ContractDefinition, error)
	ListContractDefinitionsByProject(ctx context.Context, projectID uuid.UUID) ([]ContractDefinition, error)
	ListContractEntriesBySnapshot(ctx context.Context, snapshotID uuid.UUID) ([]ProjectContractRegistry, error)
	ListEntitiesBySnapshot(ctx context.Context, snapshotID uuid.UUID) ([]ProjectEntity, error)
	ListImportArtifactsBySession(ctx context.Context, sessionID uuid.UUID) ([]ProjectImportArtifact, error)
	ListModulesBySnapshot(ctx context.Context, snapshotID uuid.UUID) ([]ProjectModule, error)
	ListProjects(ctx context.Context, workspaceID uuid.UUID) ([]Project, error)
	ListRequirementsByRoadmapItem(ctx context.Context, roadmapItemID uuid.UUID) ([]Requirement, error)
	ListRoadmapItems(ctx context.Context, projectID uuid.UUID) ([]RoadmapItem, error)
	ListSnapshotsByProject(ctx context.Context, projectID uuid.UUID) ([]ProjectIntelligenceSnapshot, error)
	ListValidationRulesByProject(ctx context.Context, projectID uuid.UUID) ([]ValidationRule, error)
	ListVariablesByContract(ctx context.Context, contractID uuid.UUID) ([]VariableDefinition, error)
	ListVariablesByProject(ctx context.Context, projectID uuid.UUID) ([]VariableDefinition, error)
	ListVersionSnapshots(ctx context.Context, roadmapItemID uuid.UUID) ([]VersionSnapshot, error)
	ListVersionSnapshotsByProject(ctx context.Context, projectID uuid.UUID) ([]VersionSnapshot, error)
	ListWebhooksByProject(ctx context.Context, projectID uuid.UUID) ([]Webhook, error)
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	UpdateAiProposalStatus(ctx context.Context, arg UpdateAiProposalStatusParams) (AiProposal, error)
	UpdateContractDefinition(ctx context.Context, arg UpdateContractDefinitionParams) (ContractDefinition, error)
	UpdateFeatureIntelligence(ctx context.Context, arg UpdateFeatureIntelligenceParams) (FeatureIntelligence, error)
	UpdateImportSession(ctx context.Context, arg UpdateImportSessionParams) (ProjectImportSession, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateRequirement(ctx context.Context, arg UpdateRequirementParams) (Requirement, error)
	UpdateRoadmapItem(ctx context.Context, arg UpdateRoadmapItemParams) (UpdateRoadmapItemRow, error)
	UpdateValidationRule(ctx context.Context, arg UpdateValidationRuleParams) (ValidationRule, error)
	UpdateVariable(ctx context.Context, arg UpdateVariableParams) (VariableDefinition, error)
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
}

var _ Querier = (*Queries)(nil)
