// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roadmap_items.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRoadmapItem = `-- name: CreateRoadmapItem :one
INSERT INTO roadmap_items (
  project_id, type, title, description, business_context, technical_context, priority, status, risk_level, readiness_level, breaking_change, regression_sensitive
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, project_id, type, title, description, business_context, technical_context, priority, status, risk_level, breaking_change, regression_sensitive, created_at, updated_at, readiness_level
`

type CreateRoadmapItemParams struct {
	ProjectID           uuid.UUID               `json:"project_id"`
	Type                RoadmapItemType         `json:"type"`
	Title               string                  `json:"title"`
	Description         sql.NullString          `json:"description"`
	BusinessContext     sql.NullString          `json:"business_context"`
	TechnicalContext    sql.NullString          `json:"technical_context"`
	Priority            NullRoadmapItemPriority `json:"priority"`
	Status              NullRoadmapItemStatus   `json:"status"`
	RiskLevel           NullRiskLevel           `json:"risk_level"`
	ReadinessLevel      sql.NullString          `json:"readiness_level"`
	BreakingChange      sql.NullBool            `json:"breaking_change"`
	RegressionSensitive sql.NullBool            `json:"regression_sensitive"`
}

func (q *Queries) CreateRoadmapItem(ctx context.Context, arg CreateRoadmapItemParams) (RoadmapItem, error) {
	row := q.db.QueryRowContext(ctx, createRoadmapItem,
		arg.ProjectID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.BusinessContext,
		arg.TechnicalContext,
		arg.Priority,
		arg.Status,
		arg.RiskLevel,
		arg.ReadinessLevel,
		arg.BreakingChange,
		arg.RegressionSensitive,
	)
	var i RoadmapItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.BusinessContext,
		&i.TechnicalContext,
		&i.Priority,
		&i.Status,
		&i.RiskLevel,
		&i.BreakingChange,
		&i.RegressionSensitive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadinessLevel,
	)
	return i, err
}

const deleteRoadmapItem = `-- name: DeleteRoadmapItem :exec
DELETE FROM roadmap_items
WHERE id = $1
`

func (q *Queries) DeleteRoadmapItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoadmapItem, id)
	return err
}

const getRoadmapItem = `-- name: GetRoadmapItem :one
SELECT id, project_id, type, title, description, business_context, technical_context, priority, status, risk_level, breaking_change, regression_sensitive, created_at, updated_at, readiness_level FROM roadmap_items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoadmapItem(ctx context.Context, id uuid.UUID) (RoadmapItem, error) {
	row := q.db.QueryRowContext(ctx, getRoadmapItem, id)
	var i RoadmapItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.BusinessContext,
		&i.TechnicalContext,
		&i.Priority,
		&i.Status,
		&i.RiskLevel,
		&i.BreakingChange,
		&i.RegressionSensitive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadinessLevel,
	)
	return i, err
}

const listRoadmapItems = `-- name: ListRoadmapItems :many
SELECT id, project_id, type, title, description, business_context, technical_context, priority, status, risk_level, breaking_change, regression_sensitive, created_at, updated_at, readiness_level FROM roadmap_items
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRoadmapItems(ctx context.Context, projectID uuid.UUID) ([]RoadmapItem, error) {
	rows, err := q.db.QueryContext(ctx, listRoadmapItems, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoadmapItem
	for rows.Next() {
		var i RoadmapItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.BusinessContext,
			&i.TechnicalContext,
			&i.Priority,
			&i.Status,
			&i.RiskLevel,
			&i.BreakingChange,
			&i.RegressionSensitive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadinessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoadmapItem = `-- name: UpdateRoadmapItem :one
UPDATE roadmap_items
  set title = $2,
  description = $3,
  business_context = $4,
  technical_context = $5,
  status = $6
WHERE id = $1
RETURNING id, project_id, type, title, description, business_context, technical_context, priority, status, risk_level, readiness_level, breaking_change, regression_sensitive, created_at, updated_at
`

type UpdateRoadmapItemParams struct {
	ID               uuid.UUID             `json:"id"`
	Title            string                `json:"title"`
	Description      sql.NullString        `json:"description"`
	BusinessContext  sql.NullString        `json:"business_context"`
	TechnicalContext sql.NullString        `json:"technical_context"`
	Status           NullRoadmapItemStatus `json:"status"`
}

type UpdateRoadmapItemRow struct {
	ID                  uuid.UUID               `json:"id"`
	ProjectID           uuid.UUID               `json:"project_id"`
	Type                RoadmapItemType         `json:"type"`
	Title               string                  `json:"title"`
	Description         sql.NullString          `json:"description"`
	BusinessContext     sql.NullString          `json:"business_context"`
	TechnicalContext    sql.NullString          `json:"technical_context"`
	Priority            NullRoadmapItemPriority `json:"priority"`
	Status              NullRoadmapItemStatus   `json:"status"`
	RiskLevel           NullRiskLevel           `json:"risk_level"`
	ReadinessLevel      sql.NullString          `json:"readiness_level"`
	BreakingChange      sql.NullBool            `json:"breaking_change"`
	RegressionSensitive sql.NullBool            `json:"regression_sensitive"`
	CreatedAt           sql.NullTime            `json:"created_at"`
	UpdatedAt           sql.NullTime            `json:"updated_at"`
}

func (q *Queries) UpdateRoadmapItem(ctx context.Context, arg UpdateRoadmapItemParams) (UpdateRoadmapItemRow, error) {
	row := q.db.QueryRowContext(ctx, updateRoadmapItem,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.BusinessContext,
		arg.TechnicalContext,
		arg.Status,
	)
	var i UpdateRoadmapItemRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.BusinessContext,
		&i.TechnicalContext,
		&i.Priority,
		&i.Status,
		&i.RiskLevel,
		&i.ReadinessLevel,
		&i.BreakingChange,
		&i.RegressionSensitive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
