// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createVersionSnapshot = `-- name: CreateVersionSnapshot :one
INSERT INTO version_snapshots (
  roadmap_item_id, snapshot_data, created_by
) VALUES (
  $1, $2, $3
)
RETURNING id, roadmap_item_id, snapshot_data, created_at, created_by
`

type CreateVersionSnapshotParams struct {
	RoadmapItemID uuid.UUID       `json:"roadmap_item_id"`
	SnapshotData  json.RawMessage `json:"snapshot_data"`
	CreatedBy     uuid.NullUUID   `json:"created_by"`
}

func (q *Queries) CreateVersionSnapshot(ctx context.Context, arg CreateVersionSnapshotParams) (VersionSnapshot, error) {
	row := q.db.QueryRowContext(ctx, createVersionSnapshot, arg.RoadmapItemID, arg.SnapshotData, arg.CreatedBy)
	var i VersionSnapshot
	err := row.Scan(
		&i.ID,
		&i.RoadmapItemID,
		&i.SnapshotData,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteVersionSnapshot = `-- name: DeleteVersionSnapshot :exec
DELETE FROM version_snapshots
WHERE id = $1
`

func (q *Queries) DeleteVersionSnapshot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVersionSnapshot, id)
	return err
}

const getVersionSnapshot = `-- name: GetVersionSnapshot :one
SELECT id, roadmap_item_id, snapshot_data, created_at, created_by FROM version_snapshots
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVersionSnapshot(ctx context.Context, id uuid.UUID) (VersionSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getVersionSnapshot, id)
	var i VersionSnapshot
	err := row.Scan(
		&i.ID,
		&i.RoadmapItemID,
		&i.SnapshotData,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listVersionSnapshots = `-- name: ListVersionSnapshots :many
SELECT id, roadmap_item_id, snapshot_data, created_at, created_by FROM version_snapshots
WHERE roadmap_item_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVersionSnapshots(ctx context.Context, roadmapItemID uuid.UUID) ([]VersionSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listVersionSnapshots, roadmapItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VersionSnapshot
	for rows.Next() {
		var i VersionSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.RoadmapItemID,
			&i.SnapshotData,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionSnapshotsByProject = `-- name: ListVersionSnapshotsByProject :many
SELECT vs.id, vs.roadmap_item_id, vs.snapshot_data, vs.created_at, vs.created_by FROM version_snapshots vs
JOIN roadmap_items ri ON vs.roadmap_item_id = ri.id
WHERE ri.project_id = $1
ORDER BY vs.created_at DESC
`

func (q *Queries) ListVersionSnapshotsByProject(ctx context.Context, projectID uuid.UUID) ([]VersionSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listVersionSnapshotsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VersionSnapshot
	for rows.Next() {
		var i VersionSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.RoadmapItemID,
			&i.SnapshotData,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
