// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: validation_rules.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createValidationRule = `-- name: CreateValidationRule :one
INSERT INTO validation_rules (
    project_id, name, rule_type, rule_config, description
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, project_id, name, rule_type, rule_config, description, created_at
`

type CreateValidationRuleParams struct {
	ProjectID   uuid.UUID             `json:"project_id"`
	Name        string                `json:"name"`
	RuleType    string                `json:"rule_type"`
	RuleConfig  pqtype.NullRawMessage `json:"rule_config"`
	Description sql.NullString        `json:"description"`
}

func (q *Queries) CreateValidationRule(ctx context.Context, arg CreateValidationRuleParams) (ValidationRule, error) {
	row := q.db.QueryRowContext(ctx, createValidationRule,
		arg.ProjectID,
		arg.Name,
		arg.RuleType,
		arg.RuleConfig,
		arg.Description,
	)
	var i ValidationRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RuleType,
		&i.RuleConfig,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteValidationRule = `-- name: DeleteValidationRule :exec
DELETE FROM validation_rules WHERE id = $1
`

func (q *Queries) DeleteValidationRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteValidationRule, id)
	return err
}

const getValidationRule = `-- name: GetValidationRule :one
SELECT id, project_id, name, rule_type, rule_config, description, created_at FROM validation_rules WHERE id = $1
`

func (q *Queries) GetValidationRule(ctx context.Context, id uuid.UUID) (ValidationRule, error) {
	row := q.db.QueryRowContext(ctx, getValidationRule, id)
	var i ValidationRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RuleType,
		&i.RuleConfig,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listValidationRulesByProject = `-- name: ListValidationRulesByProject :many
SELECT id, project_id, name, rule_type, rule_config, description, created_at FROM validation_rules WHERE project_id = $1
`

func (q *Queries) ListValidationRulesByProject(ctx context.Context, projectID uuid.UUID) ([]ValidationRule, error) {
	rows, err := q.db.QueryContext(ctx, listValidationRulesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationRule
	for rows.Next() {
		var i ValidationRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.RuleType,
			&i.RuleConfig,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateValidationRule = `-- name: UpdateValidationRule :one
UPDATE validation_rules SET
    name = $2,
    rule_type = $3,
    rule_config = $4,
    description = $5
WHERE id = $1
RETURNING id, project_id, name, rule_type, rule_config, description, created_at
`

type UpdateValidationRuleParams struct {
	ID          uuid.UUID             `json:"id"`
	Name        string                `json:"name"`
	RuleType    string                `json:"rule_type"`
	RuleConfig  pqtype.NullRawMessage `json:"rule_config"`
	Description sql.NullString        `json:"description"`
}

func (q *Queries) UpdateValidationRule(ctx context.Context, arg UpdateValidationRuleParams) (ValidationRule, error) {
	row := q.db.QueryRowContext(ctx, updateValidationRule,
		arg.ID,
		arg.Name,
		arg.RuleType,
		arg.RuleConfig,
		arg.Description,
	)
	var i ValidationRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RuleType,
		&i.RuleConfig,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
