// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: variables.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createVariable = `-- name: CreateVariable :one
INSERT INTO variable_definitions (
    contract_id, name, type, required, default_value, description, validation_rules
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, contract_id, name, type, required, default_value, description, validation_rules
`

type CreateVariableParams struct {
	ContractID      uuid.UUID             `json:"contract_id"`
	Name            string                `json:"name"`
	Type            string                `json:"type"`
	Required        sql.NullBool          `json:"required"`
	DefaultValue    sql.NullString        `json:"default_value"`
	Description     sql.NullString        `json:"description"`
	ValidationRules pqtype.NullRawMessage `json:"validation_rules"`
}

func (q *Queries) CreateVariable(ctx context.Context, arg CreateVariableParams) (VariableDefinition, error) {
	row := q.db.QueryRowContext(ctx, createVariable,
		arg.ContractID,
		arg.Name,
		arg.Type,
		arg.Required,
		arg.DefaultValue,
		arg.Description,
		arg.ValidationRules,
	)
	var i VariableDefinition
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.Name,
		&i.Type,
		&i.Required,
		&i.DefaultValue,
		&i.Description,
		&i.ValidationRules,
	)
	return i, err
}

const deleteVariable = `-- name: DeleteVariable :exec
DELETE FROM variable_definitions WHERE id = $1
`

func (q *Queries) DeleteVariable(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVariable, id)
	return err
}

const getVariable = `-- name: GetVariable :one
SELECT id, contract_id, name, type, required, default_value, description, validation_rules FROM variable_definitions WHERE id = $1
`

func (q *Queries) GetVariable(ctx context.Context, id uuid.UUID) (VariableDefinition, error) {
	row := q.db.QueryRowContext(ctx, getVariable, id)
	var i VariableDefinition
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.Name,
		&i.Type,
		&i.Required,
		&i.DefaultValue,
		&i.Description,
		&i.ValidationRules,
	)
	return i, err
}

const listVariablesByContract = `-- name: ListVariablesByContract :many
SELECT id, contract_id, name, type, required, default_value, description, validation_rules FROM variable_definitions WHERE contract_id = $1
`

func (q *Queries) ListVariablesByContract(ctx context.Context, contractID uuid.UUID) ([]VariableDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listVariablesByContract, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariableDefinition
	for rows.Next() {
		var i VariableDefinition
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.Name,
			&i.Type,
			&i.Required,
			&i.DefaultValue,
			&i.Description,
			&i.ValidationRules,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariablesByProject = `-- name: ListVariablesByProject :many
SELECT vd.id, vd.contract_id, vd.name, vd.type, vd.required, vd.default_value, vd.description, vd.validation_rules FROM variable_definitions vd
JOIN contract_definitions cd ON vd.contract_id = cd.id
JOIN roadmap_items ri ON cd.roadmap_item_id = ri.id
WHERE ri.project_id = $1
`

func (q *Queries) ListVariablesByProject(ctx context.Context, projectID uuid.UUID) ([]VariableDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listVariablesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariableDefinition
	for rows.Next() {
		var i VariableDefinition
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.Name,
			&i.Type,
			&i.Required,
			&i.DefaultValue,
			&i.Description,
			&i.ValidationRules,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVariable = `-- name: UpdateVariable :one
UPDATE variable_definitions SET
    name = $2,
    type = $3,
    required = $4,
    default_value = $5,
    description = $6,
    validation_rules = $7
WHERE id = $1
RETURNING id, contract_id, name, type, required, default_value, description, validation_rules
`

type UpdateVariableParams struct {
	ID              uuid.UUID             `json:"id"`
	Name            string                `json:"name"`
	Type            string                `json:"type"`
	Required        sql.NullBool          `json:"required"`
	DefaultValue    sql.NullString        `json:"default_value"`
	Description     sql.NullString        `json:"description"`
	ValidationRules pqtype.NullRawMessage `json:"validation_rules"`
}

func (q *Queries) UpdateVariable(ctx context.Context, arg UpdateVariableParams) (VariableDefinition, error) {
	row := q.db.QueryRowContext(ctx, updateVariable,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Required,
		arg.DefaultValue,
		arg.Description,
		arg.ValidationRules,
	)
	var i VariableDefinition
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.Name,
		&i.Type,
		&i.Required,
		&i.DefaultValue,
		&i.Description,
		&i.ValidationRules,
	)
	return i, err
}
