// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: variable_lineage.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createVariableDependency = `-- name: CreateVariableDependency :one
INSERT INTO variable_dependencies (
    source_variable_id,
    target_variable_id,
    dependency_type
) VALUES (
  $1, $2, $3
)
RETURNING id, source_variable_id, target_variable_id, dependency_type, created_at
`

type CreateVariableDependencyParams struct {
	SourceVariableID uuid.UUID   `json:"source_variable_id"`
	TargetVariableID uuid.UUID   `json:"target_variable_id"`
	DependencyType   interface{} `json:"dependency_type"`
}

func (q *Queries) CreateVariableDependency(ctx context.Context, arg CreateVariableDependencyParams) (VariableDependency, error) {
	row := q.db.QueryRowContext(ctx, createVariableDependency, arg.SourceVariableID, arg.TargetVariableID, arg.DependencyType)
	var i VariableDependency
	err := row.Scan(
		&i.ID,
		&i.SourceVariableID,
		&i.TargetVariableID,
		&i.DependencyType,
		&i.CreatedAt,
	)
	return i, err
}

const createVariableLineageEvent = `-- name: CreateVariableLineageEvent :one
INSERT INTO variable_lineage_events (
    variable_id,
    event_type,
    source_component,
    description,
    performed_by,
    metadata
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, variable_id, event_type, source_component, description, performed_by, created_at, metadata
`

type CreateVariableLineageEventParams struct {
	VariableID      uuid.UUID             `json:"variable_id"`
	EventType       interface{}           `json:"event_type"`
	SourceComponent string                `json:"source_component"`
	Description     string                `json:"description"`
	PerformedBy     uuid.NullUUID         `json:"performed_by"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateVariableLineageEvent(ctx context.Context, arg CreateVariableLineageEventParams) (VariableLineageEvent, error) {
	row := q.db.QueryRowContext(ctx, createVariableLineageEvent,
		arg.VariableID,
		arg.EventType,
		arg.SourceComponent,
		arg.Description,
		arg.PerformedBy,
		arg.Metadata,
	)
	var i VariableLineageEvent
	err := row.Scan(
		&i.ID,
		&i.VariableID,
		&i.EventType,
		&i.SourceComponent,
		&i.Description,
		&i.PerformedBy,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const deleteVariableDependencies = `-- name: DeleteVariableDependencies :exec
DELETE FROM variable_dependencies
WHERE source_variable_id = $1 OR target_variable_id = $1
`

func (q *Queries) DeleteVariableDependencies(ctx context.Context, sourceVariableID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVariableDependencies, sourceVariableID)
	return err
}

const getVariableDependencies = `-- name: GetVariableDependencies :many
SELECT id, source_variable_id, target_variable_id, dependency_type, created_at FROM variable_dependencies
WHERE source_variable_id = $1 OR target_variable_id = $1
`

func (q *Queries) GetVariableDependencies(ctx context.Context, sourceVariableID uuid.UUID) ([]VariableDependency, error) {
	rows, err := q.db.QueryContext(ctx, getVariableDependencies, sourceVariableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariableDependency
	for rows.Next() {
		var i VariableDependency
		if err := rows.Scan(
			&i.ID,
			&i.SourceVariableID,
			&i.TargetVariableID,
			&i.DependencyType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariableLineageEvents = `-- name: GetVariableLineageEvents :many
SELECT id, variable_id, event_type, source_component, description, performed_by, created_at, metadata FROM variable_lineage_events
WHERE variable_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetVariableLineageEvents(ctx context.Context, variableID uuid.UUID) ([]VariableLineageEvent, error) {
	rows, err := q.db.QueryContext(ctx, getVariableLineageEvents, variableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariableLineageEvent
	for rows.Next() {
		var i VariableLineageEvent
		if err := rows.Scan(
			&i.ID,
			&i.VariableID,
			&i.EventType,
			&i.SourceComponent,
			&i.Description,
			&i.PerformedBy,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
