// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (
    project_id, url, events, secret, active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, project_id, url, events, secret, active, created_at
`

type CreateWebhookParams struct {
	ProjectID uuid.UUID    `json:"project_id"`
	Url       string       `json:"url"`
	Events    []string     `json:"events"`
	Secret    string       `json:"secret"`
	Active    sql.NullBool `json:"active"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.ProjectID,
		arg.Url,
		pq.Array(arg.Events),
		arg.Secret,
		arg.Active,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		pq.Array(&i.Events),
		&i.Secret,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, id)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, project_id, url, events, secret, active, created_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		pq.Array(&i.Events),
		&i.Secret,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listWebhooksByProject = `-- name: ListWebhooksByProject :many
SELECT id, project_id, url, events, secret, active, created_at FROM webhooks WHERE project_id = $1
`

func (q *Queries) ListWebhooksByProject(ctx context.Context, projectID uuid.UUID) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			pq.Array(&i.Events),
			&i.Secret,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks SET
    url = $2,
    events = $3,
    secret = $4,
    active = $5
WHERE id = $1
RETURNING id, project_id, url, events, secret, active, created_at
`

type UpdateWebhookParams struct {
	ID     uuid.UUID    `json:"id"`
	Url    string       `json:"url"`
	Events []string     `json:"events"`
	Secret string       `json:"secret"`
	Active sql.NullBool `json:"active"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, updateWebhook,
		arg.ID,
		arg.Url,
		pq.Array(arg.Events),
		arg.Secret,
		arg.Active,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		pq.Array(&i.Events),
		&i.Secret,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
